# Aliases ----------------------------------------------------------

# install dotfiles
alias dotinstall="bash ~/dotfiles/install.sh"

alias ll="ls -al"
alias v="vim"
alias szh="source ~/.zshrc"
alias vzh="vim ~/.zshrc"

# git
alias g="git"
alias gs="git status"
alias gb="git branch"
alias gc="git checkout"
alias gundo="git reset --soft HEAD~1"

# tmux
alias ta="tmux attach-session -t"
alias tl="tmux ls"

# ssh
alias cssh="ssh -X danielgoldstein@login.ccs.neu.edu"
alias bdissh="ssh fep634@rescomp1.well.ox.ac.uk"

# Directories
alias projects="cd ~/Documents/Projects"
alias dots="cd ~/Documents/Projects/dotfiles"
alias ts="cd ~/Documents/college/junior-year/oxford/work/code/tskit && source tskenv/bin/activate"
alias ms="cd ~/Documents/college/junior-year/oxford/work/code/msprime && source mspenv/bin/activate"

export TERM=xterm-256color

if [ -x ~/.zprofile ]
then
    source ~/.zprofile
fi
