# Aliases ----------------------------------------------------------

# install dotfiles
alias dotinstall="bash ~/dotfiles/install.sh"

alias ll="ls -al"
alias v="nvim"
alias vimrc="nvim ~/.vimrc"
alias links="nvim useful-misc/links.txt"
alias installccls="ln -sf ~/dotfiles/linters/mac-default-ccls .ccls"

# git
alias g="git"
alias gs="git status"
alias gb="git branch"
alias gc="git checkout"
alias gundo="git reset --soft HEAD~1"

# tmux
alias ta="tmux attach-session -t"
alias tk="tmux kill-session -t"
alias tl="tmux ls"

# ssh
alias pissh="ssh pi@raspberrypi.local"

# Directories
alias projects="cd ~/Documents/Projects"
alias ts="cd ~/Documents/college/junior-year/oxford/work/new-code/tskit && source tsenv/bin/activate"
alias ms="cd ~/Documents/college/junior-year/oxford/work/code/msprime && source mspenv/bin/activate"
alias hail="cd ~/Documents/hail/hail"

export TERM=xterm-256color

if [[ $ITERM_PROFILE = gruvbox-light ]]; then
    source ~/dotfiles/zsh/gruvbox-color-overload.sh
fi

if [ -x ~/.zprofile ]
then
    source ~/.zprofile
fi
